Dev
nemanjazecevic/week1-2-task pull request #1
Opened 2021-09-10 13:47 UTC by nemanjazecevic

2021-09-13 07:41 UTC, sbozic85 commented on style.css
> +    padding: o;
Ispravi padding

2021-09-13 07:44 UTC, sbozic85 commented on style.css
> +#test{
Mogao bi da koristis neki bolji naziv ID-ja ili klase od "test", i da vidis da u CSS-u ne gadjas ID nego na neki drugi nacin da dodjes do tog elementa

2021-09-13 07:45 UTC, sbozic85 requested changes
Povezi ovaj repo sa Vercelom, kako bi mogli da vidimo kako ova grana izgleda u browseru

2021-09-13 07:47 UTC, nemanjazecevic commented
Sad cu da ispravim, pa povezujem sa vercelom. Hvala

On Mon, Sep 13, 2021 at 9:46 AM sbozic85 ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Povezi ovaj repo sa Vercelom, kako bi mogli da vidimo kako ova grana
> izgleda u browseru
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/nemanjazecevic/week1-2-task/pull/1#pullrequestreview-752414676>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOCHOAEBA2UHVJ5OULH4YNLUBWT35ANCNFSM5DZL74KA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-09-13 08:02 UTC, nemanjazecevic commented
Povezano sa vercelom, ali ne moze da se otvori jer nema nista na master grani

2021-09-17 07:29 UTC, sbozic85 approved these changes
Nemanja kod ti je generalno dobar i stranica lepo izgleda. Dve sugestije za ubuduce:
- gledaj da ne ostavljas zakomentarisan HTML i CSS kod (takodje kada dodjemo do JS-a to vazi i za console.log())
- trebalo bi da se stranica vidi lepo na svim ekranima pocevsi od 320px pa navise a tebi bas na tim malim mobilnim telefonima stranica bas ne prati dizajn ali to sada nije problem. Znaci iako su dizajn fajlovi za 375px i 1440px mi moramo da se postaramo da izgledaju lepo na svim uredjajima (ukljucujuci i telefone u landscape orijentaciji)
Inace je ovo lepo i samo ovako nastavi

2021-09-17 07:29 UTC, merged

2021-09-17 07:34 UTC, nemanjazecevic commented
Dogovoreno!
Razumeo sam da treba da odradimo samo za zadate ekrane. U buduce cu se
truditi da radim za sve rezolucije ekrana.
Hvala.

On Fri, Sep 17, 2021 at 9:30 AM sbozic85 ***@***.***> wrote:

> Merged #1 <https://github.com/nemanjazecevic/week1-2-task/pull/1> into
> master.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/nemanjazecevic/week1-2-task/pull/1#event-5317388953>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOCHOAG7KGQF54U3SG6ZVTDUCLVAHANCNFSM5DZL74KA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>